# Generated by Django 5.1.7 on 2025-04-07 11:39

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machines',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=3, quality=75, scale=None, size=[400, None], upload_to='recipes/'),
            preserve_default=3,
        ),
        migrations.AddField(
            model_name='machines',
            name='image_alt',
            field=models.CharField(max_length=100, null=3),
            preserve_default=3,
        ),
    ]
