# Generated by Django 5.1.7 on 2025-04-07 11:47

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_machines_image_machines_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=3, quality=75, scale=None, size=[400, None], upload_to='machines/'),
        ),
    ]
